"""Initial migration

Revision ID: 24d61180ed72
Revises: 
Create Date: 2025-10-11 01:39:25.236584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d61180ed72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatar_sessions_id'), 'avatar_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_avatar_sessions_session_id'), 'avatar_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_avatar_sessions_user_id'), 'avatar_sessions', ['user_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_index(op.f('ix_interviews_session_id'), 'interviews', ['session_id'], unique=True)
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    op.create_table('interview_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('communication_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('feedback_summary', sa.Text(), nullable=True),
    sa.Column('improvement_areas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_analytics_id'), 'interview_analytics', ['id'], unique=False)
    op.create_table('interview_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('technical_accuracy', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_responses_id'), 'interview_responses', ['id'], unique=False)
    op.create_table('audio_processing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_response_id', sa.Integer(), nullable=True),
    sa.Column('original_audio_url', sa.String(), nullable=True),
    sa.Column('processed_audio_url', sa.String(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_response_id'], ['interview_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_processing_id'), 'audio_processing', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_processing_id'), table_name='audio_processing')
    op.drop_table('audio_processing')
    op.drop_index(op.f('ix_interview_responses_id'), table_name='interview_responses')
    op.drop_table('interview_responses')
    op.drop_index(op.f('ix_interview_analytics_id'), table_name='interview_analytics')
    op.drop_table('interview_analytics')
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_session_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_avatar_sessions_user_id'), table_name='avatar_sessions')
    op.drop_index(op.f('ix_avatar_sessions_session_id'), table_name='avatar_sessions')
    op.drop_index(op.f('ix_avatar_sessions_id'), table_name='avatar_sessions')
    op.drop_table('avatar_sessions')
    # ### end Alembic commands ###
