# Generated by Django 5.2 on 2025-10-11 06:30

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_id'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('users', 'User').objects.update(
                avatar_id=uuid.UUID('694c83e2-8895-4a98-bd16-56332ca3f449')
            ),
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]
