# Generated by Django 4.2.7 on 2026-06-30 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('livekit_room_name', models.CharField(blank=True, default='', max_length=120)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='rooms.interviewroomtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('dimension_scores', models.JSONField(default=dict)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('raw_ai_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='interview_sessions.interviewsession')),
            ],
            options={
                'db_table': 'feedback_reports',
            },
        ),
        migrations.CreateModel(
            name='InterviewTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('asked_at', models.DateTimeField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True, default='')),
                ('answer_audio_url', models.URLField(blank=True, default='')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='interview_sessions.interviewsession')),
            ],
            options={
                'db_table': 'interview_turns',
                'ordering': ['turn_number'],
                'unique_together': {('session', 'turn_number')},
            },
        ),
    ]
