# Generated by Django 4.2.7 on 2026-06-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRoomTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('company', models.CharField(blank=True, help_text='Leave blank for generic/role-based rooms (e.g. "Amazon", "Google")', max_length=100)),
                ('role', models.CharField(help_text='e.g. "SDE-1", "Frontend Developer", "HR Generalist"', max_length=100)),
                ('round_type', models.CharField(choices=[('behavioral', 'Behavioral'), ('technical', 'Technical'), ('system_design', 'System Design'), ('hr', 'HR'), ('mixed', 'Mixed')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('interviewer_name', models.CharField(default='Alex', max_length=100)),
                ('interviewer_persona', models.TextField(help_text='Personality and style description fed to the AI.')),
                ('competencies', models.JSONField(default=list)),
                ('rubric_dimensions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interview_room_templates',
                'ordering': ['company', 'role', 'difficulty'],
            },
        ),
    ]
