# Generated by Django 4.2.7 on 2025-10-10 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewsession'),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewsession'),
        ),
    ]
