# Generated by Django 4.2.7 on 2025-10-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='avatar_id',
            field=models.UUIDField(default='694c83e2-8895-4a98-bd16-56332ca3f449'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='room_name',
            field=models.CharField(default='default-room', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='room_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
